# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸智云 - 蓝鲸桌面 (BlueKing - bkconsole) available.
Copyright (C) 2022 THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the
specific language governing permissions and limitations under the License.

We undertake not to change the open source license (MIT license) applicable

to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 1.11.29 on 2021-09-17 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210223_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='_visiable_labels',
            field=models.CharField(blank=True, db_column='visiable_labels', default='', max_length=1024, null=True, verbose_name='可见范围标签'),
        ),
        migrations.AlterField(
            model_name='app',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='app',
            name='deploy_token',
            field=models.TextField(blank=True, null=True, verbose_name='deploy_token'),
        ),
        migrations.AlterField(
            model_name='app',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('php', 'PHP')], default='python', max_length=50, null=True, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='app',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='applogo'),
        ),
        migrations.AlterField(
            model_name='app',
            name='open_mode',
            field=models.CharField(choices=[('desktop', '桌面'), ('new_tab', '新标签页')], default='desktop', max_length=20, verbose_name='应用打开方式'),
        ),
        migrations.AlterField(
            model_name='secureinfo',
            name='db_type',
            field=models.CharField(blank=True, choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('db2', 'DB2'), ('sqlserver', 'SQL Server')], default='mysql', max_length=20, null=True, verbose_name='数据库类型'),
        ),
    ]
