# Generated by Django 3.2.12 on 2022-08-04 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0032_auto_20220714_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='open_mode',
            field=models.CharField(choices=[('desktop', '桌面'), ('new_tab', '新标签页')], default='new_tab', max_length=20, verbose_name='应用打开方式'),
        ),
    ]
