# Generated by Django 3.2.12 on 2023-11-01 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0033_auto_20220804_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='star_num',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='星级评分'),
        ),
        migrations.CreateModel(
            name='AppStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_num', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='星级评分')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.app', verbose_name='应用')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='评分的用户')),
            ],
            options={
                'verbose_name': '应用评分信息',
                'verbose_name_plural': '应用评分信息',
                'db_table': 'paas_app_star',
            },
        ),
    ]
