# Generated by Django 3.2.12 on 2023-11-06 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0034_auto_20231101_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='star_num',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='星级评分'),
        )
    ]
