# Generated by Django 4.2.16 on 2025-01-10 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0035_auto_20231106_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_tenant_id',
            field=models.CharField(
                default='', help_text='应用对哪个租户的用户可用，当应用租户模式为全租户时，本字段值为空', max_length=32, verbose_name='应用租户 ID'
            ),
        ),
        migrations.AddField(
            model_name='app',
            name='app_tenant_mode',
            field=models.CharField(
                default='global', help_text='应用在租户层面的可用范围，可选值：全租户、指定租户', max_length=16, verbose_name='应用租户模式'
            ),
        ),
        migrations.AddField(
            model_name='app',
            name='tenant_id',
            field=models.CharField(
                db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID'
            ),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=20, verbose_name='应用名称'),
        ),
        migrations.AlterUniqueTogether(
            name="app",
            unique_together={("app_tenant_id", "name")},
        ),
    ]
